name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run lint
        run: |
          make init
          make check_lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: |
          pip install -e .[test]
          pytest --cov-report=xml --no-cov-on-fail
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # use token for more robust uploads
          name: ${{ matrix.python-version }}
          fail_ci_if_error: false

  all:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: All checks
    needs: [ lint, test ]
    steps:
      - name: Confirm checks passed
        if: ${{ (needs.lint.result != 'success' || needs.test.result != 'success') }}
        run: exit 1
