name: Notebooks

on: workflow_dispatch

jobs:
  test-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Graphviz
        run: sudo apt-get install graphviz
      - name: Install dependencies
        run: |
          pip install -e .[docs]
          pip install papermill
      - name: Run notebooks
        run: python -m scripts/run_notebooks/runner.py
