---
name: Slow Tests Issue Body

on:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  issues: write

jobs:
  update-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Trigger the script
        working-directory: scripts/slowest_tests
        run: source update-slowest-times-issue.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
